language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
  secure: "g5OYWupslFxzO2hMhOa+oPKVAnIqbPwMGIsPv0mkon3OMYRQdvvKhbdH+oZgaXWKIyzg26ioIFWl6UMfdEw9/pWFPuKp3VD+7qHy/WUIiPGVTtAXQMIL5sKufJixoFjltmLLz1Jv8M2YhjndbUN0zOdgHkm7Ie7XjajJRJ0rfwZRtrCXuGZPBMg+99+nCNaL3Dpqd+fGQkRo645pVIYZ+G6WXZxLPOIQyCttvXifwsoJydDuoK3Q1k3Vtt0PzmKTGUOr5LwtwU/07AITOpOsp5kE/1d2QKM5XUSSyDrKAxDkFun2/y4ZYy2y8Ds9OlCScyc5fir9SLVcvQ38dAU5HpvN0wKB2RbJ7UP6nlXbtKa8MbyZrv1OHfEjyrl/hXDPp89XzSEN27DDVQQnHWjc0lDnfh7Fg5bbQzAQQPT6hVLY7We09Hbu10xlQ6eajDqxXTZ/HCHqhITt9USAyPQdzS1g/nvWeqWBLZyn5Tc316ZOFT+isstMXy2e9tiuaLZcn3gO2OkYKHivvAUNfTkcDYKEOPAGjqgjsFI89O6YILpr1tZcbjcjHELTRMqzBUJ51Us53IGAvt1NAqoU1+OseTz4bUuNEskBVYo7DZue9P9aiRKELOukPrJBmPjUoiLanFtHZ7TV+TDK98M/Mn8vqf2PGmCMY6jhPn/fbWMWSyM="
  app: tranquil-cliffs-61578
  on:
    repo: Yitzi2/blog-app-mongoose-challenge-solution